[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read", path = "./testdata"}]

[dependencies]
forge-std = "1.9.4"
vlayer = "0.1.0-nightly-20250221-96f82e4"
"@openzeppelin-contracts" = "5.0.1"
risc0-ethereum = { version = "1.2.0", url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v1.2.0-soldeer/contracts.zip" }

[soldeer]
# whether soldeer manages remappings
remappings_generate = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false

